trigger:
- main

pr:
  autoCancel: true
  drafts: false

stages:
  - stage: test_and_build_frontend
    displayName: Test and Build Frontend
    pool:
      vmImage: 'macos-latest'

    jobs:
    - job: build
      displayName: Build

      steps:
      - checkout: self
        clean: true

      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: Install Node.js

      - bash: | 
          set -x
          npm install -g expo-cli
          npm install -g eas-cli
          npm install -g expo-updates
        displayName: Install pipeline dependencies

      - bash: |
          set -x
          expo login -u $(SHARED_EXPO_USERNAME) -p $(SHARED_EXPO_PASSWORD) --non-interactive
        displayName: Login to expo cli

      - bash: yarn install --frozen-lockfile
        displayName: Install libraries
        workingDirectory: '$(Build.Repository.LocalPath)/frontend'

      - bash: |
          set -x
          yarn test --watchAll=false
        displayName: Run Unit Tests
        workingDirectory: '$(Build.Repository.LocalPath)/frontend'

      - bash: |
          eas build --platform all --non-interactive
        displayName: Build iOS and Android for UI Testing on Azure MacOS Agent
        workingDirectory: '$(Build.Repository.LocalPath)/frontend'
        condition: and(succeeded(), eq(variables['BYuild.SourceBranch'], 'refs/heads/main'))

      - bash: |
          expo publish --non-interactive
        displayName: Publish app to expo default channel
        workingDirectory: '$(Build.Repository.LocalPath)/frontend'
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testRunner: JUnit
          testResultsFiles: '**/junit.xml'